module.exports = {
  reactStrictMode: true,

  env: {
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,
    GOOGLE_OAUTH_SCOPE: process.env.GOOGLE_OAUTH_SCOPE,

    FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID,
    FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET,
    FACEBOOK_REDIRECT_URI: process.env.FACEBOOK_REDIRECT_URI,
    FACEBOOK_OAUTH_SCOPE: process.env.FACEBOOK_OAUTH_SCOPE,
    FACEBOOK_OAUTH_FIELDS: process.env.FACEBOOK_OAUTH_FIELDS,

    BASE_API_URL: process.env.BASE_API_URL,
    DB_URI: process.env.DB_URI,
    DB_NAME: process.env.DB_NAME,
    BIGCHAINDB_URI: process.env.BIGCHAINDB_URI
  }
}
